http://localhost:8081/api
id=29a0e029-fae7-4a22-9574-f1a34e3974b4
--
http://localhost:8081/api

POST /user
{
    "email":  "someone@gmail.com",
    "amount": 10
}

--
PUT /user
{
    "_id": "4f401518-170b-4e5f-808a-c2a366ba3332",
    "email":  "someone@gmail.com",
    "amount": 20
}

--
DELETE /user
{
    "_id": "4f401518-170b-4e5f-808a-c2a366ba3332",
    "email":  "someone@gmail.com",
    "amount": 20
}

--
GET /user?id=:id

--
DELETE /user?id=:id
